### ISSUE TITLE
1.12 fail to unlock MS Store/Xbox 2.60

### ISSUE THREAD

**Issue by dwpx** [CadiLillian/eFootball-FPS-Limit-Patcher#1] opened 2023-06-16 04:06 UTC
I can use 1.12 to unlock steam app，but it will not work with MS Store app. I use UWPDumper to dump the exe and copy it to the app folder, the unlocker was useful in 2.52,but in 2.60 the unlocker will exit Immediately without any message.

**Comment by wyatsun** [comment] 2023-06-16 06:54
I have the same problem.

**Comment by dwpx** [comment] 2023-06-17 03:19
PLZ see the attachment

![unknown_2023 06 17-11 07_1](https://github.com/CadiLillian/eFootball-FPS-Limit-Patcher/assets/45808993/733b386d-bc9b-4516-9ba1-3d47932194ac)

**Comment by CadiLillian** [comment] 2023-06-17 14:47
Thank you. I have two questions after watching your video.
1. Does the patcher close itself on startup if you run it in a different directory (full access directory)?
2. Does the same thing happen with patcher version 1.11?

**Comment by dwpx** [comment] 2023-06-18 01:00
> Thank you. I have two questions after watching your video.
> 
> 1. Does the patcher close itself on startup if you run it in a different directory (full access directory)?
> 2. Does the same thing happen with patcher version 1.11?

1. The patch will start up normally in steam app folder or any other folder without efootball exe.
2. I tried 1.12 1.11 1.10 and 1.00, they have the same issue.

**Comment by CadiLillian** [comment] 2023-06-18 14:05
> 1. The patch will start up normally in steam app folder or any other folder without efootball exe.
> 2. I tried 1.12 1.11 1.10 and 1.00, they have the same issue.

All right. Based on this information, I think I know what is happening and have a possible solution for you.
Apparently Windows will let you run the patcher .exe, but won't allow you to draw a window, so it closes immediately.
File/folder access for all MS Store/Xbox applications is highly restricted, so dumping the game may not be enough to get direct access to the .exe.

You should be able to copy the dumped eFootball .exe (PesConsole-Shipping_console_wgd_Master.exe) to another location with full access rights (e.g. Desktop). Copy the patcher to the same location and run it from there. The patcher should run correctly this way and you should be able to change the FPS limit. Please try this.

Another idea that might work, but I doubt it, is to run the patcher as administrator (right click -> run as administrator).

**Comment by dwpx** [comment] 2023-06-19 06:32
> > 1. The patch will start up normally in steam app folder or any other folder without efootball exe.
> > 2. I tried 1.12 1.11 1.10 and 1.00, they have the same issue.
> 
> All right. Based on this information, I think I know what is happening and have a possible solution for you. Apparently Windows will let you run the patcher .exe, but won't allow you to draw a window, so it closes immediately. File/folder access for all MS Store/Xbox applications is highly restricted, so dumping the game may not be enough to get direct access to the .exe.
> 
> You should be able to copy the dumped eFootball .exe (PesConsole-Shipping_console_wgd_Master.exe) to another location with full access rights (e.g. Desktop). Copy the patcher to the same location and run it from there. The patcher should run correctly this way and you should be able to change the FPS limit. Please try this.
> 
> Another idea that might work, but I doubt it, is to run the patcher as administrator (right click -> run as administrator).

I have already tried these two ways，none of them worked. copy it to another folder has the same issure,  running the patcher as administrator also exit Immediately.

**Comment by CadiLillian** [comment] 2023-06-19 13:40
> I can use 1.12 to unlock steam app，but it will not work with MS Store app. I use UWPDumper to dump the exe and copy it to the app folder, the unlocker was useful in 2.52,but in 2.60 the unlocker will exit Immediately without any message.

In your first comment on this issue you stated that you could patch the steam version, this contradicts all your other comments as it implies that the patcher will work (open) as intended for you in a directory other than the MS Store/Xbox location.

> copy it to another folder has the same issure

According to your first message, you don't have this problem with the Steam version? Please explain further!

**Comment by dwpx** [comment] 2023-06-19 16:28
> > I can use 1.12 to unlock steam app，but it will not work with MS Store app. I use UWPDumper to dump the exe and copy it to the app folder, the unlocker was useful in 2.52,but in 2.60 the unlocker will exit Immediately without any message.
> 
> In your first comment on this issue you stated that you could patch the steam version, this contradicts all your other comments as it implies that the patcher will work (open) as intended for you in a directory other than the MS Store/Xbox location.
> 
> > copy it to another folder has the same issure
> 
> According to your first message, you don't have this problem with the Steam version? Please explain further!

Maybe you can give me your email, I will send you the MS Store/Xbox exe, you can try to reproduce the issue so you can find the problem.

**Comment by CadiLillian** [comment] 2023-06-20 13:07
> I think you have misunderstanded the situation，the problem is the unlocker can not open the MS Store/Xbox exe and it doesn't related with the permissions or folder. I can open the unlocker in MS Store/Xbox folder after deleting the MS Store/Xbox exe, it will show ' efootball executable not found' message. I can also open the unlocker with steam app exe. so I think the problem is the new 2.60 MS Store/Xbox exe can't be edited by the old way，maybe it needs new way to do that

Interesting. I will look into it, but I need some more information.
The next question is based on this statement:
> so I think the problem is the new 2.60 MS Store/Xbox exe can't be edited by the old way，maybe it needs new way to do that

Have previous versions of the patcher worked for you with previous versions of the MS Store/Xbox eFootball .exe? (e.g. Patcher version 1.11 with eFootball version 2.5.1)

**Comment by dwpx** [comment] 2023-06-21 10:10
> > I think you have misunderstanded the situation，the problem is the unlocker can not open the MS Store/Xbox exe and it doesn't related with the permissions or folder. I can open the unlocker in MS Store/Xbox folder after deleting the MS Store/Xbox exe, it will show ' efootball executable not found' message. I can also open the unlocker with steam app exe. so I think the problem is the new 2.60 MS Store/Xbox exe can't be edited by the old way，maybe it needs new way to do that
> 
> Interesting. I will look into it, but I need some more information. The next question is based on this statement:
> 
> > so I think the problem is the new 2.60 MS Store/Xbox exe can't be edited by the old way，maybe it needs new way to do that
> 
> Have previous versions of the patcher worked for you with previous versions of the MS Store/Xbox eFootball .exe? (e.g. Patcher version 1.11 with eFootball version 2.5.1)

I have unlocked  MS Store/Xbox eFootball .exe 2.52 by the unlocker 1.00

**Comment by CadiLillian** [comment] 2023-06-25 21:30
This is now fixed in update 1.20.
I have also added offline optimization for MS Store eFootball version 2.6.0 for instant patching times.

Update 1.20 also introduces an update check + notification (pop-up) on startup.

**Closed by CadiLillian** 2023-06-25 21:30 UTC
Labels: bug, question

**Comment by dwpx** [comment] 2023-06-26 09:07
> This is now fixed in update 1.20. I have also added offline optimization for MS Store eFootball version 2.6.0 for instant patching times.
> 
> Update 1.20 also introduces an update check + notification (pop-up) on startup.

THX，I've tried the 1.20， it works perfectly.
